### ISSUE TITLE
ld: library not found for -lscapix

### ISSUE THREAD

**Issue by AlexanderNorway** [scapix-com/example1#2]
Hi Boris,

I cloned the repositories:
```
$ mkdir scapix
$ cd scapix
$ git clone https://github.com/scapix-com/example1
$ git clone https://github.com/scapix-com/scapix
```
ran:
```
xcode_ios_objc.sh
```
opened:
```
chat.xcworkspace
```

I also tried:
```
xcode_ios_objc_sim.sh
```

however, Im getting:
```
ld: library not found for -lscapix
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Running the script isn't giving any visible errors or relevant warnings.

Using:
Xcode v11.2.1

Any help is appreciated!

**Comment by Boris-Rasin** [comment]
Thanks for reporting this issue.
I believe I've fixed it (https://github.com/scapix-com/scapix/commit/8a26f51f848ade4f48c5c2e23675bba535aa8a74), please update Scapix repository and try again.
Make sure to run a clean build.

If it still doesn't work, please reopen this issue.

**Comment by AlexanderNorway** [comment]
Thanks a lot for fixing it so quickly 🥇  !!
Btw, Github doesn't let people reopen issues that have been closed by a repo collaborator for some reason... so to avoid getting duplicate issues, its probably a good idea to wait for confirmation before closing an issue. It was not needed in this case 👍
